"""Every screen in the app, as one searchable list.

The navbar can only show a handful of these at a time and the rest live two
hovers deep, so the search box needs its own index. Each entry carries the
permission key its menu used, and the search filters on that - a destination
a user cannot open is a destination they should not be offered.

Generated from base.html, report_all.html and vouchers_dashboard.html, then
kept by hand. test_navigation checks every endpoint here still resolves.
"""

# (label, where it lives, endpoint, url arguments, permission key)
DESTINATIONS = [
    ('Dashboard', 'Main', 'dashboard_bp.dashboard', {}, ''),
    ('Chart of Accounts', 'Accounting Master', 'master_bp.chart_of_accounts', {}, 'accounting_master.chart_of_accounts'),
    ('Manage Groups', 'Accounting Master', 'master_bp.manage_groups', {}, 'accounting_master.groups'),
    ('Manage Sub Groups', 'Accounting Master', 'master_bp.manage_sub_groups', {}, 'accounting_master.sub_groups'),
    ('Manage Ledgers', 'Accounting Master', 'master_bp.manage_ledgers', {}, 'accounting_master.ledgers'),
    ('Manage Customers', 'Accounting Master', 'master_bp.manage_parties', {'kind': 'customers'}, 'accounting_master.ledgers'),
    ('Manage Vendors', 'Accounting Master', 'master_bp.manage_parties', {'kind': 'vendors'}, 'accounting_master.ledgers'),
    ('Manage Credit Terms', 'Accounting Master', 'master_bp.manage_credit_terms', {}, 'accounting_master.credit_terms'),
    ('Manage Cost Centers', 'Accounting Master', 'master_bp.manage_cost_centers', {}, 'accounting_master.cost_centers'),
    ('Asset Register', 'Modules > Fixed Assets', 'fixed_asset_bp.assets', {}, 'modules.fixed_assets'),
    ('New Asset', 'Modules > Fixed Assets', 'fixed_asset_bp.add_asset', {}, 'modules.fixed_assets'),
    ('Run Depreciation', 'Modules > Fixed Assets', 'fixed_asset_bp.run_depreciation', {}, 'modules.fixed_assets'),
    ('Templates', 'Modules > Recurring', 'recurring_bp.templates', {}, 'modules.recurring'),
    ('New Template', 'Modules > Recurring', 'recurring_bp.add_template', {}, 'modules.recurring'),
    ('Process Due Entries', 'Modules > Recurring', 'recurring_bp.process_entries', {}, 'modules.recurring'),
    ('Manage Inventory Groups', 'Inventory Master', 'master_bp.manage_inventory_groups', {}, 'inventory_master.inventory_groups'),
    ('Manage Inventory', 'Inventory Master', 'master_bp.manage_inventory', {}, 'inventory_master.inventory'),
    ('Selling Price Master', 'Inventory Master', 'master_bp.manage_selling_prices', {}, 'inventory_master.inventory'),
    ('Vendor Item Mappings', 'Inventory Master', 'master_bp.vendor_item_mappings', {}, 'inventory_master.vendor_item_mappings'),
    ('Vouchers', 'Main', 'voucher_bp.vouchers', {}, 'vouchers'),
    ('POS', 'Main', 'pos_bp.pos', {}, 'vouchers'),
    ('Reports', 'Main', 'report_bp.report_all', {}, 'reports'),
    ('Print Documents', 'Print', 'print_bp.print_documents', {}, 'print'),
    ('JV print', 'Print', 'print_bp.print_jv', {}, 'print.jv_print'),
    ('Import Queue', 'Main', 'import_bp.import_queue', {}, 'import_queue'),
    ('Company Settings', 'Setup', 'company_bp.company_settings', {}, 'setup.company_settings'),
    ('Manage Financial Years', 'Setup', 'financial_year_bp.manage_financial_years', {}, 'setup.financial_years'),
    ('Voucher Configuration', 'Setup', 'admin_config_bp.voucher_config_page', {}, 'setup.voucher_config'),
    ('Voucher Numbering', 'Setup', 'admin_config_bp.voucher_numbering_page', {}, 'setup.voucher_config'),
    ('User Management', 'Setup', 'auth_bp.admin', {}, 'setup.user_management'),
    ('AI Settings', 'Admin', 'ai_settings_bp.ai_settings', {}, 'setup.user_management'),
    ('Admin Management', 'Admin', 'auth_bp.admin_management', {}, 'setup.user_management'),
    ('Settlement / Matching', 'Modules', 'settlement_bp.index', {}, 'modules.settlement'),
    ('Balance Sheet', 'Reports > Financial Statements', 'report_bp.report_balance_sheet', {}, 'reports'),
    ('Profit & Loss', 'Reports > Financial Statements', 'report_bp.report_profit_and_loss', {}, 'reports'),
    ('Trial Balance', 'Reports > Financial Statements', 'report_bp.report_trial_balance', {}, 'reports'),
    ('Cash Flow Statement', 'Reports > Financial Statements', 'report_bp.report_cash_flow', {}, 'reports'),
    ('General Ledger', 'Reports > Ledger Books', 'report_bp.report_ledger_transactions', {}, 'reports'),
    ('Customer Ledger', 'Reports > Ledger Books', 'report_bp.report_customer_ledger', {}, 'reports'),
    ('Supplier Ledger', 'Reports > Ledger Books', 'report_bp.report_supplier_ledger', {}, 'reports'),
    ('Bank Book', 'Reports > Ledger Books', 'report_bp.report_bank_book', {}, 'reports'),
    ('Cash Book', 'Reports > Ledger Books', 'report_bp.report_cash_book', {}, 'reports'),
    ('Ageing Report', 'Reports > Ledger Books', 'report_bp.report_ageing', {}, 'reports'),
    ('Party Matching', 'Reports > Ledger Books', 'report_bp.report_party_matching', {}, 'reports'),
    ('Daybook', 'Reports > Registers', 'report_bp.report_daybook', {}, 'reports'),
    ('GL Dump', 'Reports > Registers', 'report_bp.report_gl_dump', {}, 'reports'),
    ('Payment Register', 'Reports > Registers', 'report_bp.report_register', {'voucher_type': 'Payment'}, 'reports'),
    ('Receipt Register', 'Reports > Registers', 'report_bp.report_register', {'voucher_type': 'Receipt'}, 'reports'),
    ('Journal Register', 'Reports > Registers', 'report_bp.report_register', {'voucher_type': 'Journal'}, 'reports'),
    ('Contra Register', 'Reports > Registers', 'report_bp.report_register', {'voucher_type': 'Contra'}, 'reports'),
    ('Sales Register', 'Reports > Registers', 'report_bp.report_register', {'voucher_type': 'Sales'}, 'reports'),
    ('Purchase Register', 'Reports > Registers', 'report_bp.report_register', {'voucher_type': 'Purchase'}, 'reports'),
    ('Sales Return Register', 'Reports > Registers', 'report_bp.report_register', {'voucher_type': 'Sales Return'}, 'reports'),
    ('Purchase Return Register', 'Reports > Registers', 'report_bp.report_register', {'voucher_type': 'Purchase Return'}, 'reports'),
    ('Sales Summary', 'Reports > Registers', 'report_bp.report_sales_summary', {}, 'reports'),
    ('Purchase Summary', 'Reports > Registers', 'report_bp.report_purchase_summary', {}, 'reports'),
    ('Profit by Item', 'Reports > Registers', 'report_bp.report_profit_by_item', {}, 'reports'),
    ('Profit by Customer', 'Reports > Registers', 'report_bp.report_profit_by_customer', {}, 'reports'),
    ('Expense Register', 'Reports > Registers', 'report_bp.report_register', {'voucher_type': 'Expense'}, 'reports'),
    ('Stock Summary', 'Reports > Inventory Reports', 'report_bp.report_stock_summary', {}, 'reports'),
    ('Stock Valuation', 'Reports > Inventory Reports', 'report_bp.report_stock_valuation', {}, 'reports'),
    ('Stock Movement', 'Reports > Inventory Reports', 'report_bp.report_stock_movement', {}, 'reports'),
    ('Closing Inventory', 'Reports > Inventory Reports', 'report_bp.report_closing_inventory', {}, 'reports'),
    ('Slow / Non-Moving', 'Reports > Inventory Reports', 'report_bp.report_slow_moving', {}, 'reports'),
    ('Negative Stock', 'Reports > Inventory Reports', 'report_bp.report_negative_stock', {}, 'reports'),
    ('Inventory Ageing', 'Reports > Inventory Reports', 'report_bp.report_inventory_ageing', {}, 'reports'),
    ('VAT Summary', 'Reports > VAT Reports', 'report_bp.report_vat_summary', {}, 'reports'),
    ('VAT Detailed', 'Reports > VAT Reports', 'report_bp.report_vat_detailed', {}, 'reports'),
    ('Expense VAT', 'Reports > VAT Reports', 'report_bp.report_vat_expense', {}, 'reports'),
    ('Service Income VAT', 'Reports > VAT Reports', 'report_bp.report_vat_service_income', {}, 'reports'),
    ('Statement of Account', 'Reports > Tools', 'report_bp.report_statement_of_account', {}, 'reports'),
    ('Verify Books', 'Reports > Tools', 'report_bp.verify_books', {}, 'reports'),
    ('Report Builder', 'Reports > Tools', 'report_builder_bp.report_builder_page', {}, 'reports'),
    ('Find / Edit Voucher', 'Vouchers', 'voucher_bp.edit_voucher_search', {}, 'vouchers'),
    ('New Receipt', 'Vouchers', 'voucher_bp.voucher', {'voucher_type': 'receipt'}, 'vouchers'),
    ('New Payment', 'Vouchers', 'voucher_bp.voucher', {'voucher_type': 'payment'}, 'vouchers'),
    ('New Contra', 'Vouchers', 'voucher_bp.voucher', {'voucher_type': 'contra'}, 'vouchers'),
    ('New Journal', 'Vouchers', 'voucher_bp.voucher', {'voucher_type': 'journal'}, 'vouchers'),
    ('New Expense', 'Vouchers', 'voucher_bp.voucher', {'voucher_type': 'expense'}, 'vouchers'),
    ('New Service Income', 'Vouchers', 'voucher_bp.voucher', {'voucher_type': 'service_income'}, 'vouchers'),
    ('New Service Income Return', 'Vouchers', 'voucher_bp.voucher', {'voucher_type': 'service_income_return'}, 'vouchers'),
    ('Sales Orders', 'Vouchers', 'order_bp.orders', {'order_slug': 'sales'}, 'vouchers'),
    ('Purchase Orders', 'Vouchers', 'order_bp.orders', {'order_slug': 'purchase'}, 'vouchers'),
    ('New Sales', 'Vouchers', 'voucher_bp.voucher', {'voucher_type': 'sales'}, 'vouchers'),
    ('New Sales Return', 'Vouchers', 'voucher_bp.voucher', {'voucher_type': 'sales_return'}, 'vouchers'),
    ('New Purchase', 'Vouchers', 'voucher_bp.voucher', {'voucher_type': 'purchase'}, 'vouchers'),
    ('New Purchase Return', 'Vouchers', 'voucher_bp.voucher', {'voucher_type': 'purchase_return'}, 'vouchers'),
    ('New Additional Charges', 'Vouchers', 'voucher_bp.voucher', {'voucher_type': 'additional_charges'}, 'vouchers'),
    ('New Stock Adjustment', 'Vouchers', 'voucher_bp.voucher', {'voucher_type': 'stock_adjustment'}, 'vouchers'),
    ('New Inventory Transfer', 'Vouchers', 'voucher_bp.voucher', {'voucher_type': 'inventory_transfer'}, 'vouchers'),
    ('Reverse Voucher', 'Vouchers', 'voucher_bp.reverse_voucher_page', {}, 'vouchers'),
]
